services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"   # Minecraft client
      - "25575:25575"   # RCON (Terraform provider talks to this)
    environment:
      EULA: "TRUE"
      MODE: "creative"
      DIFFICULTY: "peaceful"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "terraform"
      RCON_PORT: "25575"